# Generated by Django 5.1.6 on 2025-02-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0002_alter_users_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='added_by_user_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pincode',
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(blank=True, choices=[('Congo', 'Congo'), ('Tanzania', 'Tanzania'), ('Angola', 'Angola'), ('Zambia', 'Zambia'), ('Burundi', 'Burundi')], default='Congo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='currency',
            field=models.CharField(blank=True, choices=[('CDF', 'CDF'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='CDF', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='departMent',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Production', 'Production'), ('Maintenance', 'Maintenance'), ('Engineering', 'Engineering'), ('Consulting', 'Consulting'), ('Management', 'Management'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='designation',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('CFO', 'CFO'), ('CTO', 'CTO'), ('CMO', 'CMO'), ('COO', 'COO'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='domain_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('French', 'French')], default='English', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='time_zone',
            field=models.CharField(blank=True, choices=[('UTC-12:00', 'UTC-12:00'), ('UTC-11:00', 'UTC-11:00'), ('UTC-10:00', 'UTC-10:00'), ('UTC-09:30', 'UTC-09:30'), ('UTC-09:00', 'UTC-09:00'), ('UTC-08:00', 'UTC-08:00'), ('UTC-07:00', 'UTC-07:00'), ('UTC-06:00', 'UTC-06:00'), ('UTC-05:00', 'UTC-05:00'), ('UTC-04:00', 'UTC-04:00'), ('UTC-03:30', 'UTC-03:30'), ('UTC-03:00', 'UTC-03:00'), ('UTC-02:00', 'UTC-02:00'), ('UTC-01:00', 'UTC-01:00'), ('UTC', 'UTC'), ('UTC+01:00', 'UTC+01:00'), ('UTC+02:00', 'UTC+02:00'), ('UTC+03:00', 'UTC+03:00'), ('UTC+03:30', 'UTC+03:30'), ('UTC+04:00', 'UTC+04:00'), ('UTC+04:30', 'UTC+04:30'), ('UTC+05:00', 'UTC+05:00'), ('UTC+05:30', 'UTC+05:30'), ('UTC+05:45', 'UTC+05:45'), ('UTC+06:00', 'UTC+06:00'), ('UTC+06:30', 'UTC+06:30'), ('UTC+07:00', 'UTC+07:00'), ('UTC+08:00', 'UTC+08:00'), ('UTC+08:45', 'UTC+08:45'), ('UTC+09:00', 'UTC+09:00'), ('UTC+09:30', 'UTC+09:30'), ('UTC+10:00', 'UTC+10:00'), ('UTC+10:30', 'UTC+10:30'), ('UTC+11:00', 'UTC+11:00'), ('UTC+12:00', 'UTC+12:00'), ('UTC+12:45', 'UTC+12:45'), ('UTC+13:00', 'UTC+13:00'), ('UTC+14:00', 'UTC+14:00')], default='UTC+02:00', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usershippingaddress',
            name='country',
            field=models.CharField(choices=[('Congo', 'Congo'), ('Tanzania', 'Tanzania'), ('Angola', 'Angola'), ('Zambia', 'Zambia'), ('Burundi', 'Burundi')], max_length=50),
        ),
    ]
