# Generated by Django 5.1.6 on 2025-03-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0003_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.TextField(default='no-image'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
