# Generated by Django 5.1.6 on 2025-03-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0004_alter_categories_image_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.TextField(),
        ),
    ]
